const ADD_PRODUCTS = "ADD_PRODUCTS";
const EDIT_PRODUCTS = "EDIT_PRODUCTS";
const DELETE_PRODUCT = "DELETE_PRODUCT";
const SEE_DETAIL = "SEE_DETAIL";
const ADD_TO_CART = "ADD_TO_CART";
const REMOVE_FROM_CART = "REMOVE_FROM_CART"
export { ADD_PRODUCTS, EDIT_PRODUCTS, DELETE_PRODUCT, SEE_DETAIL,ADD_TO_CART , REMOVE_FROM_CART};